version: '3.8'

services:
  mongodb:
    build: .
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Espone la porta di MongoDB
    volumes:
      - mongodb_data:/data/db

  fastapi_app:
    build: .
    container_name: mongodb_api
    restart: always
    ports:
      - "8094:8094"  # Espone la porta dell'app FastAPI
    depends_on:
      - mongodb
#    environment:
#      - MONGO_HOST=mongodb
#      - MONGO_PORT=27017

volumes:
  mongodb_data:
